### ISSUE TITLE
Bezier Surface 

### ISSUE THREAD

**Issue by alyfreym** [drewcrawford/blitcurve#4]
Hi it is possible using this lib create  2D Bezier Surface? (Then im planning map image on it, creating kind of warp effect) 
Bellow image examples. 
<img width="333" alt="Screenshot 2023-05-21 at 20 05 20" src="https://github.com/drewcrawford/blitcurve/assets/29518174/c15161cb-3854-45ad-8b2e-38e9ec282087">

**Comment by drewcrawford** [comment]
At the moment there is no support for 2d surfaces. I’ve done some generalization separately to higher dimensions. There are standard approaches. However there are some problems using those approaches for my situation, so they were not very useful.
